[build]
  command = "yarn build:all"
  functions = "packages/lambda/dist/" #  netlify-lambda reads this
  publish = "packages/client/build/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
